# Generated by Django 3.0.3 on 2020-02-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='timestamp',
        ),
    ]
